webservers:
  hosts:
    157.55.87.81:
      package_name: apache2
      php_modules:
        -  php
        -  libapache2-mod-php
        -  php-mysql
        -  php-cli
    35.170.60.145:
      package_name: httpd
      php_modules:
        -  php
        -  php-mysql
        -  php-cli
