-  hosts: all
   become: yes
   tasks:
     -  name: install htppd
        yum:
          name: htppd
          state: present
     -  name: enable and restart htppd
        service:
          name: htppd
          enabled: yes
          state: restarted
     -  name: install php
        yum:
          name: php
          state: present
     -  name: install php-mysql
        yum:
          name: php-mysql
          state: present
     -  name: install php-mysql
        yum:
          name: php-mysql
          state: present
     -  name: restart htppd
        service:
          name: htppd
          state: restarted
                                   