-  hosts: all
   become: yes
   tasks:
     -  name: install httpd
        yum:
          name: httpd
          state: present
        notify:
          -  enable and restart htppd
     -  name: install php modules
        yum:
          name: "{{ item }}"
          state: present
        loop:
          -  php
          -  php-mysql
          -  php-cli
        notify:
          -  enable and restart httpd         
   handlers:
     -  name: enable and restart httpd
        service:
          name: httpd
          enabled: yes
          state: restarted
