-  hosts: all
   become: yes
   tasks:
     -  name: install httpd
        yum:
          name: httpd
          state: present
     -  name: enable and restart httpd
        service:
          name: httpd
          enabled: yes
          state: restarted
     -  name: install php
        yum:
          name: php
          state: present
     -  name: install php-mysql
        yum:
          name: php-mysql
          state: present
     -  name: install php-mysql
        yum:
          name: php-mysql
          state: present
     -  name: restart httpd
        service:
          name: httpd
          state: restarted
                                   